### ISSUE TITLE
能说说chronos的业务应用场景吗

### ISSUE THREAD

**Issue by peiliping** [XiaoMi/chronos#10]

**Comment by tobegit3hub** [comment]
我回复下，Chronos实现了生成全局严格单调递增（也是唯一）的timestamp服务，使用场景在README提到。

```
提供全局严格单调递增的timestamp，用于实现Percolator等全局性事务。
提供全局唯一的值，相比snowflake不依赖NTP服务，并且提供failover机制。
```

**Comment by tobegit3hub** [comment]
Can this help? @peiliping 

It would be better to close this if it answers your question.
