### ISSUE TITLE
Chronos的原理及集群环境支持

### ISSUE THREAD

**Issue by uliian** [XiaoMi/chronos#7]
我想了解一下Chronos的自增是依靠什么机制来实现的？按照介绍我推测是通过本机（服务端）的时间来实现。不知是否正确。
如果是按照本机的时间来实现递增且不重复的话，集群环境下就要求集群内所有机器时间必须是一致的，不知这个推测是否正确？

**Comment by tobegit3hub** [comment]
Hi @uliian 

Chronos自增机制是这样的，master进程的内存维护一个变量，每次分配时检查系统时间，如果系统时间比这个变量大则返回系统时间，如果系统时间比较小（时间偏移或是同一毫秒内的请求）则返回这个变量加上一。这样做的好处是首先确保返回值一定是严格单调递增的，其次是返回值尽量与系统时间保持一致方便使用者调试。

Chronos是master/slave架构，同一时刻只有一台master接受请求并返回结果，这时集群其他slave并不需要同步时间，即使同步也有可能有时间偏移。为了解决单点问题，master接受请求前会把一个未分配到的大值写到zk上，如果master挂了，slave抢主并成为主后会从zk的这个值开始分配，保证正确性 :smiley:

**Comment by uliian** [comment]
理解了，非常感谢！

**Comment by tobegit3hub** [comment]
不客气 @uliian :smile:
